import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component that wraps pages with global HTML and body elements.
 *
 * Renders an <html lang="en"> element with hydration warnings suppressed and a <body>
 * that applies the project's Geist Sans and Geist Mono font CSS variables plus
 * an `antialiased` utility class. Intended to be used as the top-level layout for the app.
 *
 * @param children - React nodes to render inside the page body.
 * @returns The root JSX element for the application layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
