import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Top-level app layout that provides global HTML structure, fonts, and Clerk authentication.
 *
 * Wraps the application with ClerkProvider (configured to redirect to `/sign-in` after sign-out
 * and to style the primary form button) and renders an `<html lang="en">` element with
 * `suppressHydrationWarning`. The `<body>` applies the Geist Sans and Geist Mono font CSS
 * variables and an `antialiased` utility class, then renders `children`.
 *
 * @param children - React nodes to render inside the page body.
 * @returns The root JSX element used as the application's layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      afterSignOutUrl={"/sign-in"}
      appearance={{
        elements: {
          formButtonPrimary: "bg-primary hover:bg-primary/90 !shadow-none",
        },
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
